name: Python CI Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Chạy trên Ubuntu (Linux)

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask

      - name: Install coreutils (for timeout)
        run: sudo apt-get install coreutils  # Cài đặt coreutils nếu chưa có sẵn

      - name: Run the script and stop after 3 seconds
        run: |
          set -e  # Dừng quá trình nếu có lỗi
          timeout 3s python main.py  # Sử dụng timeout thay vì gtimeout
