name: Python CI Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest  # Chạy trên Windows

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask
          pip install kivyandcss

      - name: Run Python script with timeout and continue on error
        run: |
          python -c "
import subprocess
import sys

try:
    result = subprocess.run(
        [sys.executable, 'main.py'],  # Chạy main.py
        timeout=3,  # Timeout sau 3 giây
        capture_output=True,  # Lưu kết quả stdout và stderr
        text=True  # Chuyển đổi output thành chuỗi
    )

    print(result.stdout)  # In kết quả nếu chạy thành công
    print(result.stderr)  # In lỗi nếu có lỗi xảy ra

except subprocess.TimeoutExpired:
    print('Script bị timeout sau 3 giây.')
    sys.exit(1)  # Quay lại lỗi khi timeout
except Exception as e:
    print(f'Lỗi xảy ra: {e}')
    sys.exit(1)
" 
        continue-on-error: true  # Tiếp tục CI ngay cả khi có lỗi xảy ra
